=== mims96/Proyectos-DAW/Primer_curso/Lenguajes de Marcas y Gestión de la Información/Actividad 2/Noelia/Biblioteca.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="documentos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="libros">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="libro" maxOccurs="unbounded"> <!--Pueden haber muchas ocurrencias de libros que pertenezcan a un determinado tipo de clase: novela, infantil, didactica-->
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulo" type="xs:string"></xs:element> <!-- El valor maxOccurs en caso de no indicarse por defecto es 1-->
                                                    <xs:element name="indice" type="xs:string"></xs:element>
                                                    <xs:element name="capitulos">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="capitulo" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="titulo" type="xs:string"></xs:element>
                                                                            <xs:element name="contenido">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="informacion" type="xs:string"></xs:element>
                                                                                    </xs:sequence>
                                                                                    <xs:attribute name="enlace" type="xs:string"></xs:attribute>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="paginas_capitulo" type="xs:integer" use="required"></xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="sinopsis" type="xs:string"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:pattern value="[L][0-9]{4}"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="tipo_clase" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="novela"/>
                                                            <xs:enumeration value="infantil"/>
                                                            <xs:enumeration value="didactico"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="paginas_libro" type="xs:integer" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="revistas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="revista" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulo" type="xs:string"></xs:element>
                                                    <xs:element name="numero" type="xs:string"></xs:element>
                                                    <xs:element name="indice" type="xs:string"></xs:element>
                                                    <xs:element name="secciones">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="seccion" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="contenido">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="informacion" type="xs:string"></xs:element>
                                                                                    </xs:sequence>
                                                                                    <xs:attribute name="enlace" type="xs:string"/>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="paginas_seccion" type="xs:integer" use="required"/>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:pattern value="[R][1-5]{1}"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="tipo_clase" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="informatica"/>
                                                            <xs:enumeration value="corazon"/>
                                                            <xs:enumeration value="coches"/>
                                                            <xs:enumeration value="investigacion"/>
                                                            <xs:enumeration value="otras"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="paginas_revista" type="xs:integer" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="periodicos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="periodico" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="indice" type="xs:string"></xs:element>
                                                    <xs:element name="seccionesPeriodico">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="seccionPeriodico" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="articulo" maxOccurs="unbounded">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="contenido">
                                                                                            <xs:complexType>
                                                                                                <xs:sequence>
                                                                                                    <xs:element name="informacion" type="xs:string"></xs:element>
                                                                                                </xs:sequence>
                                                                                                <xs:attribute name="enlace" type="xs:string"/>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                    <xs:attribute name="autor" type="xs:string" use="required"/>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="tipo_seccion" use="required">
                                                                            <xs:simpleType>
                                                                                <xs:restriction base="xs:string">
                                                                                    <xs:enumeration value="economica"/>
                                                                                    <xs:enumeration value="opinion"/>
                                                                                    <xs:enumeration value="deportes"/>
                                                                                    <xs:enumeration value="nacional"/>
                                                                                    <xs:enumeration value="internacional"/>
                                                                                </xs:restriction>
                                                                            </xs:simpleType>
                                                                        </xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:string"/>
                                                <xs:attribute name="tipo_clase" type="xs:string"/>
                                                <xs:attribute name="fecha_publicacion" type="xs:string"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mims96/Proyectos-DAW/Primer_curso/Lenguajes de Marcas y Gestión de la Información/Actividad 2/Noelia/Biblioteca2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation= "Biblioteca.xsd">



    <documentos>
    
        <libros>
            <libro id="L0001" tipo_clase="novela" paginas_libro="1000"> 
            
                <titulo></titulo>
                <indice></indice>

                <capitulos>

                    <capitulo paginas_capitulo="50">
                        <titulo></titulo>
                        <contenido enlace="enlace_capitulo1">
                            <informacion></informacion> <!-- La información deberá de ir como nodo elemento a no ser que se especifique lo contrario-->
                        </contenido> 
                    </capitulo>

                    <capitulo  paginas_capitulo="70">
                        <titulo></titulo>
                        <contenido enlace="enlace_capitulo2">
                            <informacion></informacion> 
                        </contenido>
                    </capitulo>

                </capitulos>

                <sinopsis>
                </sinopsis>
            
            </libro>

            <libro id="L0002" tipo_clase="infantil" paginas_libro="2000"> 
            
                <titulo></titulo>
                <indice></indice>

                <capitulos>

                    <capitulo paginas_capitulo="60">
                        <titulo></titulo>
                        <contenido enlace="enlace_capitulo1">
                            <informacion></informacion> 
                        </contenido> 
                    </capitulo>

                    <capitulo paginas_capitulo="90">
                        <titulo></titulo>
                        <contenido enlace="enlace_capitulo2">
                            <informacion></informacion> 
                        </contenido>
                    </capitulo>

                </capitulos>

                <sinopsis>
                </sinopsis>
            
            </libro>

            <libro id="L0003" tipo_clase="didactico" paginas_libro="1250"> 
            
                <titulo></titulo>
                <indice></indice>

                <capitulos>

                    <capitulo paginas_capitulo="120">
                        <titulo>¿titulo?</titulo>
                        <contenido enlace="enlace_capitulo1">
                            <informacion></informacion> 
                        </contenido> 
                    </capitulo>

                    <capitulo paginas_capitulo="20">
                        <titulo></titulo>
                        <contenido enlace="enlace_capitulo2">
                            <informacion></informacion> 
                        </contenido>
                    </capitulo>

                </capitulos>

                <sinopsis>
                </sinopsis>

            </libro>

        </libros>
     

        <revistas>

            <revista id="R1" tipo_clase="informatica" paginas_revista="20">
                <titulo></titulo>
                <numero></numero>
                <indice></indice>
                <secciones>
                    <seccion paginas_seccion="5">
                        <contenido enlace="enlace_seccion_1">
                            <informacion></informacion> 
                        </contenido>
                    </seccion>
                    <seccion paginas_seccion="15">
                        <contenido enlace="enlace_seccion_2">
                            <informacion></informacion> 
                        </contenido>
                    </seccion>
                </secciones>
            </revista>
            <revista id="R2" tipo_clase="corazon" paginas_revista="30">
                <titulo></titulo>
                <numero></numero>
                <indice></indice>
                <secciones>
                    <seccion paginas_seccion="20">
                        <contenido enlace="enlace_seccion_1">
                            <informacion></informacion> 
                        </contenido>
                    </seccion>
                    <seccion paginas_seccion="10">
                        <contenido enlace="enlace_seccion_2">
                            <informacion></informacion> 
                        </contenido>
                    </seccion>
                </secciones>
            </revista>

            <revista id="R3" tipo_clase="coches" paginas_revista="40">
                <titulo></titulo>
                <numero></numero>
                <indice></indice>
                <secciones>
                    <seccion paginas_seccion="20">
                        <contenido enlace="enlace_seccion_1">
                            <informacion></informacion> 
                        </contenido>
                    </seccion>
                    <seccion paginas_seccion="20">
                        <contenido enlace="enlace_seccion_2">
                            <informacion></informacion> 
                        </contenido>
                    </seccion>
                </secciones>
            </revista>

            <revista id="R4" tipo_clase="investigacion" paginas_revista="50">
                <titulo></titulo>
                <numero></numero>
                <indice></indice>
                <secciones>
                    <seccion paginas_seccion="30">
                        <contenido enlace="enlace_seccion_1">
                             <informacion></informacion> 
                        </contenido>
                    </seccion>
                    <seccion paginas_seccion="20">
                        <contenido enlace="enlace_seccion_2">
                             <informacion></informacion> 
                        </contenido>
                    </seccion>
                </secciones>
            </revista> 

            <revista id="R5" tipo_clase="otras" paginas_revista="60">
                <titulo></titulo>
                <numero></numero>
                <indice></indice>
                <secciones> 
                    <seccion paginas_seccion="30">
                        <contenido enlace="enlace_seccion_1">
                            <informacion></informacion> 
                        </contenido>
                    </seccion>
                    <seccion paginas_seccion="30">
                        <contenido enlace="enlace_seccion_2">    
                            <informacion></informacion> 
                        </contenido>
                    </seccion>
                </secciones>
            </revista>

        </revistas>

        <periodicos>

            <periodico id="P0001" tipo_clase="nacionales" fecha_publicacion="10/10/2022">
                <indice></indice>
                <seccionesPeriodico>
                    <seccionPeriodico tipo_seccion="economica">
                        <articulo autor="anonimo">
                            <contenido enlace="enlace_info_articulo_1">
                                <informacion></informacion> 
                            </contenido>
                        </articulo>
                    </seccionPeriodico>
                </seccionesPeriodico>
            </periodico>       

            <periodico id="P0002" tipo_clase="internacionales" fecha_publicacion="10/10/2022">
                <indice></indice>
                <seccionesPeriodico>
                    <seccionPeriodico tipo_seccion="opinion">
                        <articulo autor="anonimo">
                            <contenido enlace="enlace_info_articulo_1">
                                <informacion></informacion> 
                            </contenido> 
                        </articulo>
                    </seccionPeriodico>
                </seccionesPeriodico>

            </periodico>   
            
        </periodicos>

    </documentos>

</Biblioteca>
