=== mims96/Proyectos-DAW/Primer_curso/Lenguajes de Marcas y Gestión de la Información/Actividad 2/Gerard/xml/biblioteca.dtd
<!--DECLARO LAS ETIQUETAS DE LA CABEZERA DE LA BIBLIOTECA-->
<!ELEMENT Biblioteca (Documentos)>
<!ELEMENT Documentos (libros, revistas, periodicos)>

<!--DECLARO TODAS LAS ETIQUETAS DE TIENEN QUE CONTENER LOS LIBROS-->
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo, indice, capitulos, sinopsis)>
<!ELEMENT capitulos (capitulo+)>
<!ELEMENT capitulo (contenido)>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>

<!--DECLARO LOS ATRIBUTOS DE LAS ETIQUETAS QUE HACEN REFERENCIA A LOS LIBROS-->
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro tipo (novela | infantil | didactico) #REQUIRED>
<!ATTLIST libro paginas CDATA #REQUIRED>
<!ATTLIST capitulo paginas CDATA #REQUIRED>

<!--DECLARO LAS ETIQUETAS PARA LAS REVISTAS-->
<!ELEMENT revistas (revista+)>
<!ELEMENT revista (titulo, indice, secciones)>
<!ELEMENT secciones (seccion+)>
<!ELEMENT seccion (contenido)>


<!--DECLARO LOS ATRIBUTOS DE LAS REVISTAS-->
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista paginas CDATA #REQUIRED>
<!ATTLIST revista tipo (informatica | corazon | coches | investigacion | otras) #REQUIRED>
<!ATTLIST seccion paginas CDATA #REQUIRED>


<!--DECLARO LAS ETIQUETAS PARA LOS PERIODICOS-->
<!ELEMENT periodicos (periodico+)>
<!ELEMENT periodico (titulo, indice, sections, contenido)>
<!ELEMENT sections (section+)>
<!ELEMENT section (articulo)>

<!ELEMENT articulo (#PCDATA)>



<!--DECLARO LOS ATRIBUTOS DE LAS ETIQUETAS-->
<!ATTLIST periodico id ID #REQUIRED>
<!ATTLIST periodico tipo (nacionales | internacionales) #REQUIRED>
<!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>
<!ATTLIST section clase (economica | opinion | deportes | nacional | internacional) #REQUIRED>
<!ATTLIST articulo autor CDATA #REQUIRED>

=== mims96/Proyectos-DAW/Primer_curso/Lenguajes de Marcas y Gestión de la Información/Actividad 2/Gerard/xml/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE Biblioteca SYSTEM "biblioteca.dtd">-->
<Biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="biblioteca.xsd">
<!--<Biblioteca>-->
    <Documentos>
        <libros>
            <libro id="L0001" tipo="novela" paginas="768">
                <titulo>Lejos de Luisiana</titulo>
                <indice>El indice esta en la pagina 8 </indice>
                <capitulos>
                    <capitulo paginas="15">
                        <contenido> 
                            Explica el comienzo 
                        </contenido>
                    </capitulo>
                    <capitulo paginas="10">
                        <contenido>
                            Explica el curso medio de la transicion
                        </contenido>
                    </capitulo> 
                </capitulos>
                <sinopsis>
                    Después de años de colonización, la familia Girard acepta la controvertida decisión de su país, Francia, de ceder a España en 1763 parte de las indómitas 
                    tierras del Misisipi; sin embargo, sufrirá las consecuencias de las rebeliones de sus compatriotas contra los españoles, la guerra de norteamericanos contra 
                    ingleses por la independencia de los Estados Unidos y la lucha desesperada de los nativos indios por la supervivencia de sus pueblos. 
                    En unos tiempos tan convulsos, Suzette Girard e Ishcate, indio de la tribu kaskaskia, librarán su propia batalla: preservar su amor de las amenazas 
                    del mundo que les ha tocado vivir. Todo ello conforma una novela cautivadora y monumental que atraviesa las cuatro décadas en las que España poseyó las 
                    legendarias tierras de Luisiana.
                </sinopsis>
            </libro>
            <libro id="L0002" tipo="infantil" paginas="44">
                <titulo>El Elefante Rosado</titulo>
                <indice>Esta en la pagina 2</indice>
                <capitulos>
                    <capitulo paginas="10">
                        <contenido>
                            primer capitulo
                        </contenido>
                    </capitulo>
                    <capitulo paginas="5">
                        <contenido>
                            segundo capitulo
                        </contenido>
                    </capitulo>
                </capitulos>
                <sinopsis>
                    Cuento de Inteligencia Emocional y Pensamiento Positivo que incentiva la constancia, la empatía, la confianza y la autoestima.
                    Un Elefante diferente ayuda al pequeño Daniel a conocer la forma de conseguir las cosas que le hacen feliz como encestar canastas en baloncesto, 
                    montar bien en bici sin ayudas, entre otros logros..
                </sinopsis>
            </libro>
            <libro id="L0003" tipo="didactico" paginas="108">
                <titulo>Caligrafia divertida con pauta montessori</titulo>
                <indice>Esta en la pagina 4</indice>
                <capitulos>
                    <capitulo paginas="10">
                        <contenido>
                            Escritura basica
                        </contenido>
                    </capitulo>
                    <capitulo paginas="15">
                        <contenido>
                            Escritura avanzada
                        </contenido>
                    </capitulo>
                </capitulos>
                <sinopsis>
                    ①Lee el chiste o acertijo gracioso y échate unas risas. Además, mejoras tu comprensión lectora* y te libras del estrés. ¿Qué estrés? -Dos más uno.
                    *Comprensión lectora: Como lees para "pillar" el chiste, entrenas tu atención lectora. No debes responder a preguntas para demostrar que lo has entendido, 
                    tu risa lo hará.
                    ②Repasa los trazos de letra clara, comprensible y bonita para iniciarte con confianza en la escritura.
                    ③ Escribe. La pauta Montessori te marca los límites de todos los trazos para que consigas una escritura bonita y perfectamente formada. 
                    Mantén la concentración, la repetición te ayuda a memorizar el chiste y podrás regalar risas y buen humor a tus amigos y familia cuando se los cuentes.
                    ④Colorea los dibujos que acompañan los chistes para personalizar tu caligrafía y hacerla única.
                    Tu letra va a mejorar tanto que te van a dar unas ganas locas de estudiar tus apuntes o incluso de enmarcarlos.
                </sinopsis>
            </libro>
        </libros>
        <revistas>
            <revista id="R0001" paginas="40" tipo="informatica">
                <titulo>Computer Hoy</titulo>
                <indice>En la pagina 2</indice>
                <secciones> 
                    <seccion paginas="20">
                        <contenido>
                            Actualidad
                        </contenido>
                    </seccion>
                    <seccion paginas="22">
                        <contenido>
                            Práctico, navegadores web, digitalizacion
                        </contenido>
                    </seccion>
                    <seccion paginas="15">
                        <contenido>
                            Test de nuevos dispositivos
                        </contenido>
                    </seccion>
                </secciones>
            </revista>
            <revista id="R0002" paginas="55" tipo="corazon">
                <titulo>¡HOLA!</titulo>
                <indice>Es la pagina 4</indice>
                <secciones>
                    <seccion paginas="15">
                        <contenido>
                            Actualidad
                        </contenido>
                    </seccion>
                    <seccion paginas="20">
                        <contenido>
                            Moda, tendencias 
                        </contenido>
                    </seccion>
                    <seccion paginas="20">
                        <contenido>
                            Lifestyle, nutricion
                        </contenido>
                    </seccion>
                </secciones>
            </revista>
            <revista id="R0003" paginas="60" tipo="coches">
                <titulo>Motor_16</titulo>
                <indice>Es la pagina 3</indice>
                <secciones>
                    <seccion paginas="20">
                        <contenido>
                            Nuevos modelos de coches
                        </contenido>
                    </seccion>
                    <seccion paginas="20">
                        <contenido>
                            Las nuevas tecnologias
                        </contenido>
                    </seccion>
                    <seccion paginas="20">
                        <contenido>
                            Mercado de segunda mano
                        </contenido>
                    </seccion>
                </secciones>
            </revista>
            <revista id="R0004" paginas="70" tipo="investigacion">
                <titulo>National Geographic</titulo>
                <indice>Es en la pagina 2</indice>
                <secciones>
                    <seccion paginas="20">
                        <contenido>
                            El arca de la alianza
                        </contenido>
                    </seccion>
                    <seccion paginas="30">
                        <contenido>
                            Faraones Negros
                        </contenido>
                    </seccion>
                    <seccion paginas="20">
                        <contenido>
                            Alejandro Magno y Filipo
                        </contenido>
                    </seccion>
                </secciones>
            </revista>
            <revista id="R0005" paginas="30" tipo="otras">
                <titulo>HobbyConsolas</titulo>
                <indice>Es en la pagina 4</indice>
                <secciones>
                    <seccion paginas="8">
                        <contenido>
                            Reportaje the legend of zelda: Tears of the Kingdom
                        </contenido>
                    </seccion>
                    <seccion paginas="20">
                        <contenido>
                            Analisis de diferentes juegos
                        </contenido>
                    </seccion>
                    <seccion paginas="2">
                        <contenido>
                            El rincon del coleccionista
                        </contenido>
                    </seccion>
                </secciones>
            </revista>
        </revistas>
        <periodicos> 
            <periodico id="P0001" tipo="nacionales" fecha_publicacion="2023-04-29">
                <titulo>El Mundo</titulo>
                <indice>En la pagina 2</indice>
                <sections>
                    <section clase="economica">
                        <articulo autor="El mundo madrid">
                        Las petroleras piden al Gobierno que les escuche
                        </articulo>
                    </section>
                    <section clase="opinion">
                        <articulo autor="Andres trapiello">
                            Modelos feministas: Zenobia camprubi aymar
                        </articulo>
                    </section>
                    <section clase="deportes">
                        <articulo autor="Lucas Saez-Bravo">
                            España ya conoce su camino en el mundial
                        </articulo>
                    </section>
                    <section clase="nacional">
