=== mims96/Proyectos-DAW/Primer_curso/Lenguajes de Marcas y Gestión de la Información/Actividad 2/Maria_Isabel/xsd_maria_isabel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <element name="biblioteca">
        <complexType>
            <sequence>
                <element name="libros">
                    <complexType>
                        <sequence>
                            <element name="libro" maxOccurs="unbounded">
                                <complexType>
                                    <sequence>
                                        <element name="titulo" type="string"/>
                                        <element name="capitulos">
                                            <complexType>
                                                <sequence>
                                                    <element name="capitulo" minOccurs="1" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="titulocapitulo" type="string"/>
                                                                <element name="contenido">
                                                                    <complexType>
                                                                    <attribute name="href" use="required"/>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="paginas" type="integer" use="required"/>
                                                        </complexType>
                                                    </element>    
                                                </sequence>
                                            </complexType>
            
                                        </element>
                                        <element name="indice" type="string"/>
                                        <element name="sinopsis" type="string"/>
                                    </sequence>
                                    <attribute name ="id" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <pattern value="[L]{1}[0-9]{4}"></pattern> 
                                            </restriction>
                                        </simpleType>
                                    </attribute> 
                                    <attribute name ="tipo_clase" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <enumeration value="novela"/>
                                                <enumeration value="infantil"/>
                                                <enumeration value="did치ctico"/>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name ="paginas" type="integer" use="required"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>

                <element name="revistas">
                    <complexType>
                        <sequence>
                            <element name="revista" minOccurs="1" maxOccurs="unbounded">
                                <complexType>
                                    <sequence>
                                        <element name="titulorevista" type="string"/>
                                        <element name="numero" type="integer"/>
                                        <element name="indicerevista" type="string"/>
                                        <element name="secciones">
                                            <complexType>
                                                <sequence>
                                                    <element name="seccion" minOccurs="1" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="nombre" type="string"/>
                                                                <element name="contenidorevista">
                                                                    <complexType>
                                                                        <attribute name="href" use="required"/>
                                                                    </complexType> 
                                                                </element>
                                                            </sequence>
                                                            <attribute name="paginas" type="integer" use="required"/>
                                                        </complexType>
                                                    </element>    
                                                </sequence>
                                            </complexType> 
                                        </element>
                                    </sequence>
                                    <attribute name ="id" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <pattern value="[R]{1}[0-9]{4}"></pattern>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name ="tipo_clase" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <enumeration value="inform치tica"/>
                                                <enumeration value="coraz칩n"/>
                                                <enumeration value="coches"/>
                                                <enumeration value="investigaci칩n"/>
                                                <enumeration value="otras"/>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name ="paginas" type="integer" use="required"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>


                <element name="periodicos">
                    <complexType>
                        <sequence>
                            <element name="periodico" minOccurs="1" maxOccurs="unbounded"> 
                                <complexType>
                                    <sequence>
                                        <element name="tituloperiodico" type="string"/>
                                        <element name="indiceperiodico" type="string"/>
                                        <element name="seccionesperiodico">
                                            <complexType>
                                                <sequence> 
                                                    <element name="seccionperiodico" minOccurs="1" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="articulo" maxOccurs="unbounded">
                                                                    <complexType mixed="true">
                                                                        <sequence>
                                                                            <element name ="contenidoperiodico">
                                                                                <complexType>   
                                                                                    <attribute name="href" use="required"/>
                                                                                </complexType>
                                                                            </element>
                                                                        </sequence>
                                                                        <attribute name="autor" type="string" use="required"/>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="tipo" type="string" use="required"/>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name ="id" use="required">
                                        <simpleType>
                                            <restriction base="string">
                                                <pattern value="[P]{1}[0-9]{4}"></pattern>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name ="tipo_clase" use="required">
                                        <simpleType>  
                                            <restriction base="string">
                                                <enumeration value="nacional"/>
                                                <enumeration value="internacional"/>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name ="publicacion" type="string" use="required"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>  
                </element>    
            </sequence>
        </complexType>
    </element>
</schema>

=== mims96/Proyectos-DAW/Primer_curso/Lenguajes de Marcas y Gestión de la Información/Actividad 2/Maria_Isabel/mariaisabel_xmldtd.xml
<?xml version="1.0" encoding="UTF-8"?>
   <!--                               
                                    Se crea el DTD interno
<!DOCTYPE biblioteca[
    <!ELEMENT biblioteca (libros, revistas, periodicos)>

                        Se crean los elementos y atributos de libros
    <!ELEMENT libros (libro+)>
    <!ATTLIST libro id ID #REQUIRED>
    <!ATTLIST libro tipo_clase (novela | infantil | didáctico) #REQUIRED>
    <!ATTLIST libro paginas CDATA #REQUIRED>
    <!ELEMENT libro (titulo, capitulos, indice, sinopsis)>

    <!ELEMENT titulo (#PCDATA)>

    <!ELEMENT capitulos (capitulo+)>
    <!ATTLIST capitulo paginas CDATA #REQUIRED>
    <!ELEMENT capitulo (titulocapitulo, contenido)>
    <!ELEMENT titulocapitulo (#PCDATA)>
    <!ELEMENT contenido EMPTY>
    <!ATTLIST contenido href CDATA #REQUIRED>

    <!ELEMENT indice (#PCDATA)>

    <!ELEMENT sinopsis (#PCDATA)>



                        Se crean los elementos y atributos de revistas
    <!ELEMENT revistas (revista+)>
    <!ATTLIST revista id ID #REQUIRED>
    <!ATTLIST revista tipo_clase (informática | corazón | coches | investigación | otras) #REQUIRED>
    <!ATTLIST revista paginas CDATA #REQUIRED>
    <!ELEMENT revista (titulorevista, numero, indicerevista, secciones)>

    <!ELEMENT titulorevista (#PCDATA)>

    <!ELEMENT numero (#PCDATA)>  

    <!ELEMENT indicerevista (#PCDATA)>

    <!ELEMENT secciones (seccion+)>
    <!ATTLIST seccion paginas CDATA #REQUIRED>
    <!ELEMENT seccion (nombre, contenidorevista)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT contenidorevista EMPTY>
    <!ATTLIST contenidorevista href CDATA #REQUIRED>


                        Se crean los elementos y atributos de periodicos
    <!ELEMENT periodicos (periodico+)>
    <!ATTLIST periodico id ID #REQUIRED>
    <!ATTLIST periodico tipo_clase (nacional | internacional) #REQUIRED>
    <!ATTLIST periodico publicacion CDATA #REQUIRED>
    <!ELEMENT periodico (tituloperiodico, indiceperiodico, seccionesperiodico)>

    <!ELEMENT tituloperiodico (#PCDATA)>

    <!ELEMENT indiceperiodico (#PCDATA)>

    <!ELEMENT seccionesperiodico (seccionperiodico+)>
    <!ATTLIST seccionperiodico tipo CDATA #REQUIRED>
    <!ELEMENT seccionperiodico (articulo+)>
    <!ATTLIST articulo autor CDATA #REQUIRED>
    <!ELEMENT articulo (#PCDATA|contenidoperiodico)*>
    <!ELEMENT contenidoperiodico EMPTY>
    <!ATTLIST contenidoperiodico href CDATA #REQUIRED>
    
]>

-->






<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="xsd_maria_isabel.xsd">
<!--La etiqueta padre de todo el XML es biblioteca.
    Dentro de ella se encuentran libros, revistas y periódicos y, a su vez, 
    dentro de estos hay más elementos que se presentarán a continuación. -->
 <!--<biblioteca>-->                                            <!--Libros-->  
    <libros>
        <libro id="L1234" tipo_clase="novela" paginas="448">
            <titulo>Madame Bovary</titulo>
            <capitulos>
                <capitulo paginas ="10">
                    <titulocapitulo>Capítulo 1</titulocapitulo>
                    <contenido href="https://www.casadellibro.com/libro-madame-bovary/9788467033915/1777854"></contenido>
                </capitulo>
                <capitulo paginas ="10">
                    <titulocapitulo>Capítulo 2</titulocapitulo>
                    <contenido href="https://www.casadellibro.com/libro-madame-bovary/9788467033915/1777854"></contenido>
                </capitulo>
                <capitulo paginas ="6">
                    <titulocapitulo>Capítulo 3</titulocapitulo>
                    <contenido href="https://www.casadellibro.com/libro-madame-bovary/9788467033915/1777854"></contenido>
                </capitulo>
            </capitulos>
            <indice>
                Capítulo 1 página 11
                Capítulo 2 página 21
                Capítulo 3 página 31
            </indice>
            <sinopsis>La soñadora Emma, una joven de provincias casada con Charles Bovary, quien la ama pero es incapaz de comprenderla y satisfacerla, buscará la realización de sus sueños en otros amores, pasionales y platónicos..., pero ninguno de ellos logrará calmar su desesperada ansiedad y sus románticas inquietudes.</sinopsis>
        </libro>

        <libro id="L5678" tipo_clase="infantil" paginas="96">
            <titulo>El principito</titulo>
            <capitulos>
                <capitulo paginas ="4">
                    <titulocapitulo>Cómo me hice piloto</titulocapitulo>
                    <contenido href="https://www.amazon.es/Principito-Antoine-Saint-Exup%C3%A9ry-Saint-Exupery/dp/8498381495"></contenido>
                </capitulo>
                <capitulo paginas ="6"> 
                    <titulocapitulo>Cómo conocí al principito</titulocapitulo>
                    <contenido href="https://www.amazon.es/Principito-Antoine-Saint-Exup%C3%A9ry-Saint-Exupery/dp/8498381495"></contenido>
                </capitulo>
                <capitulo paginas ="16">
                    <titulocapitulo>El planeta del principito</titulocapitulo>
                    <contenido href="https://www.amazon.es/Principito-Antoine-Saint-Exup%C3%A9ry-Saint-Exupery/dp/8498381495"></contenido>
                </capitulo>
            </capitulos>
            <indice>
                Capítulo 1 página 7
                Capítulo 2 página 11
                Capítulo 3 página 17
            </indice>
            <sinopsis>Fábula mítica y relato filosófico que interroga acerca de la relación del ser humano con su prójimo y con el mundo, El Principito concentra, con maravillosa simplicidad, la constante reflexión de Saint-Exupéry sobre la amistad, el amor, la responsabilidad y el sentido de la vida.</sinopsis>
        </libro>

        <libro id="L9182" tipo_clase="didáctico" paginas="176">
            <titulo>Cartas sobre Educación Infantil</titulo>
            <capitulos>
                <capitulo paginas ="1">
                    <titulocapitulo>Carta 1</titulocapitulo>
                    <contenido href="https://www.casadellibro.com/libro-cartas-sobre-educacion-infantil-3-ed/9788430944194/1103028"></contenido>
                    </capitulo>
                <capitulo paginas ="1">
                    <titulocapitulo>Carta 2</titulocapitulo>
                    <contenido href="https://www.casadellibro.com/libro-cartas-sobre-educacion-infantil-3-ed/9788430944194/1103028"></contenido>
                </capitulo>
                <capitulo paginas ="2"> 
                    <titulocapitulo>Carta 3</titulocapitulo>
                    <contenido href="https://www.casadellibro.com/libro-cartas-sobre-educacion-infantil-3-ed/9788430944194/1103028"></contenido>
                </capitulo>
            </capitulos>
            <indice>
                Capítulo 1 página 3
                Capítulo 2 página 3
                Capítulo 3 página 4 
            </indice>
            <sinopsis>Entre las variadas obras de Pestalozzi, en sus Cartas sobre educación infantil es donde mejor describe sus ideas pedagógicas. Se trata de una obra de síntesis, compuesta en su ancianidad con el propósito de dar una visión ordenada y completa de su pensamiento y de sus experiencias tras una vida entera dedicada a la labor y a la técnica de la escuela.</sinopsis>
        </libro>
    </libros>

                                             <!--Revistas-->
    <revistas>
        <revista id="R1234" tipo_clase="informática" paginas="74">
            <titulorevista>Computer Hoy</titulorevista>
            <numero>641</numero>
            <indicerevista>
                Top 5 página 5
                Foto de la semana página 6
                El tema de la semana página 8
            </indicerevista>
            <secciones>
                <seccion paginas="22">
                    <nombre>Actualidad</nombre>
                    <contenidorevista href="https://store.axelspringer.es/tecnologia/revistas-tecnologia/computer-hoy/n-641-computer-hoy.html"></contenidorevista>
                </seccion>
                <seccion paginas="18">
                    <nombre>Práctico</nombre>
                    <contenidorevista href="https://store.axelspringer.es/tecnologia/revistas-tecnologia/computer-hoy/n-641-computer-hoy.html"></contenidorevista>
                </seccion>
                <seccion paginas="16">
                    <nombre>Test</nombre>
                    <contenidorevista href="https://store.axelspringer.es/tecnologia/revistas-tecnologia/computer-hoy/n-641-computer-hoy.html"></contenidorevista>
                </seccion>
                <seccion paginas="12"> 
                    <nombre>Saber más</nombre>
                    <contenidorevista href="https://store.axelspringer.es/tecnologia/revistas-tecnologia/computer-hoy/n-641-computer-hoy.html"></contenidorevista>
                </seccion>
            </secciones>
        </revista>

        <revista id="R5678" tipo_clase="corazón" paginas="78">
            <titulorevista>Lecturas</titulorevista>
            <numero>3388</numero> 
            <indicerevista>
                Torito página 4
                Siete Días página 10
                Kike Calleja página 16 
            </indicerevista> 
            <secciones>
                <seccion paginas="60">
                    <nombre>Reportajes</nombre>
                    <contenidorevista href="https://play.google.com/store/apps/details?id=es.rba.lecturas.android"></contenidorevista>
                </seccion>
                <seccion paginas="12">
                    <nombre>Actualidad</nombre>
                    <contenidorevista href="https://play.google.com/store/apps/details?id=es.rba.lecturas.android"></contenidorevista>
                </seccion>
                <seccion paginas="1">
                    <nombre>Pasatiempos</nombre>
                    <contenidorevista href="https://play.google.com/store/apps/details?id=es.rba.lecturas.android"></contenidorevista>
